language: python
python:
  # Ansible only supports Python 2 for now, and anything less than 2.7 sucks.
  - "2.7"
install: "pip install -r requirements.txt"
script: make test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
